INSERT INTO users (username, email, password, first_name, last_name)
  VALUES ('jmcginty15', 'jason_mcginty@yahoo.com', '$2b$13$WVwloIwEa.wcmzHYFzmaQeO9AGtz8SDeJGgde0u80lP.oTTxqta1C', 'Jason', 'McGinty'),
         ('zach_mcginty', 'zach_mcginty@yahoo.com', 'password', 'Zach', 'McGinty'),
         ('godelchess', 'godel_chess@yahoo.com', 'password', 'Dennis', 'Baker'),
         ('Toranaga-Minowara', 'toranaga_minowara@yahoo.com', 'password', 'Jake', 'Wilson'),
         ('lawbooks10', 'law_books@yahoo.com', 'password', 'Brian', 'Reeves'),
         ('Dwang_ho', 'dwang_ho@yahoo.com', 'password', 'Britt', 'Hoover'),
         ('PDavison', 'p_davison@yahoo.com', 'password', 'Paul', 'Davison'),
         ('Macondo_Iceman', 'macondo_iceman@yahoo.com', 'password', 'Jeff', 'Rooney'),
         ('pawannelson', 'pawan_nelson@yahoo.com', 'password', 'Pawan', 'Nelson'),
         ('harbed_325', 'harbed@yahoo.com', 'password', 'Edward', 'Harbeck'),
         ('afader', 'a_fader@yahoo.com', 'password', 'Alex', 'Fader'),
         ('Iarwain_Ben-adar', 'iarwain_ben_adar@yahoo.com', 'password', 'Joe', 'Davis'),
         ('BrianHellstrom', 'brian_hellstrom@yahoo.com', 'password', 'Brian', 'Hellstrom'),
         ('Hegemon78', 'hegemon_78@yahoo.com', 'password', 'Adam', 'Darby'),
         ('pjamison', 'p_jamison@yahoo.com', 'password', 'Paul', 'Jamison'),
         ('Capt_Sal', 'capt_sal@yahoo.com', 'password', 'Sal', 'Randazzo');

INSERT INTO ind_tournaments (director,
                             name,
                             time_control,
                             category,
                             min_players,
                             max_players,
                             rounds,
                             round_length,
                             registration_open,
                             registration_close,
                             start_date)
  VALUES ('jmcginty15',
          'Inaugural OGB Online Chess Championship',
          '30|30',
          'classical',
          12,
          16,
          6,
          7,
          '2020-10-31T18:00:00Z',
          '2020-11-06T18:00:00Z',
          '2020-11-06T18:00:00Z');

INSERT INTO ind_entries (player, tournament, seed, rating, score, sonneborn_berger_score, place, prev_opponents, prev_colors)
  VALUES ('jmcginty15', 1, 0, 1826, 0, 0, 0, '', ''),
         ('zach_mcginty', 1, 0, 1922, 0, 0, 0, '', ''),
         ('godelchess', 1, 0, 2164, 0, 0, 0, '', ''),
         ('Toranaga-Minowara', 1, 0, 1691, 0, 0, 0, '', ''),
         ('lawbooks10', 1, 0, 1418, 0, 0, 0, '', ''),
         ('Dwang_ho', 1, 0, 1368, 0, 0, 0, '', ''),
         ('PDavison', 1, 0, 1090, 0, 0, 0, '', ''),
         ('Macondo_Iceman', 1, 0, 1626, 0, 0, 0, '', ''),
         ('pawannelson', 1, 0, 1543, 0, 0, 0, '', ''),
         ('harbed_325', 1, 0, 1311, 0, 0, 0, '', ''),
         ('afader', 1, 0, 1546, 0, 0, 0, '', ''),
         ('Iarwain_Ben-adar', 1, 0, 1620, 0, 0, 0, '', ''),
         ('BrianHellstrom', 1, 0, 1294, 0, 0, 0, '', ''),
         ('Hegemon78', 1, 0, 1640, 0, 0, 0, '', ''),
         ('pjamison', 1, 0, 1231, 0, 0, 0, '', ''),
         ('Capt_Sal', 1, 0, 1132, 0, 0, 0, '', '');
