UPDATE ind_games SET result = '1-0' WHERE id = 1;
UPDATE ind_games SET result = '0.5-0.5' WHERE id = 2;
UPDATE ind_games SET result = '0.5-0.5' WHERE id = 3;
UPDATE ind_games SET result = '0-1' WHERE id = 4;
UPDATE ind_games SET result = '0.5-0.5' WHERE id = 5;
UPDATE ind_games SET result = '0.5-0.5' WHERE id = 6;
UPDATE ind_games SET result = '1-0' WHERE id = 7;

UPDATE ind_entries SET score = 1 WHERE player = 'godelchess';
UPDATE ind_entries SET score = 0.5 WHERE player = 'Macondo_Iceman';
UPDATE ind_entries SET score = 0.5 WHERE player = 'harbed_325';
UPDATE ind_entries SET score = 0.5 WHERE player = 'BrianHellstrom';
UPDATE ind_entries SET score = 0.5 WHERE player = 'Toranaga-Minowara';
UPDATE ind_entries SET score = 1 WHERE player = 'zach_mcginty';
UPDATE ind_entries SET score = 0.5 WHERE player = 'PDavison';
UPDATE ind_entries SET score = 0.5 WHERE player = 'pawannelson';
UPDATE ind_entries SET score = 0.5 WHERE player = 'Iarwain_Ben-adar';
UPDATE ind_entries SET score = 0.5 WHERE player = 'pjamison';
UPDATE ind_entries SET score = 1 WHERE player = 'lawbooks10';
