UPDATE ind_games SET result = '0-1' WHERE id = 9;
UPDATE ind_games SET result = '1-0' WHERE id = 10;
UPDATE ind_games SET result = '0.5-0.5' WHERE id = 11;
UPDATE ind_games SET result = '0.5-0.5' WHERE id = 12;
UPDATE ind_games SET result = '0.5-0.5' WHERE id = 13;
UPDATE ind_games SET result = '0.5-0.5' WHERE id = 14;
UPDATE ind_games SET result = '1-0' WHERE id = 15;

UPDATE ind_entries SET score = 2 WHERE player = 'godelchess';
UPDATE ind_entries SET score = 2 WHERE player = 'jmcginty15';
UPDATE ind_entries SET score = 1 WHERE player = 'BrianHellstrom';
UPDATE ind_entries SET score = 1 WHERE player = 'Macondo_Iceman';
UPDATE ind_entries SET score = 1 WHERE player = 'Toranaga-Minowara';
UPDATE ind_entries SET score = 1 WHERE player = 'harbed_325';
UPDATE ind_entries SET score = 1 WHERE player = 'Iarwain_Ben-adar';
UPDATE ind_entries SET score = 1 WHERE player = 'PDavison';
UPDATE ind_entries SET score = 1 WHERE player = 'pjamison';
UPDATE ind_entries SET score = 1 WHERE player = 'pawannelson';
UPDATE ind_entries SET score = 1 WHERE player = 'Dwang_ho';
